version: "3.9"

services:
  backend:
    build: ./backend
    container_name: gitverse-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    # No command override here — use CMD from Dockerfile!

  frontend:
    build:
      context: ./frontend
    container_name: gitverse-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]

