{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className | default "nginx" }}
spec:
  controller: k8s.io/ingress-nginx
{{- end }}
