replicaCount: 1

image:
  repository: riyajoshi/gitverse-frontend
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: gitverse.local
      paths:
        - path: /
          pathType: Prefix
  tls: []  # no TLS for now

resources: {}
