ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: gitverse.local
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend-service
              port: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port: 80
  tls: []
