name: container

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - '.github/workflows/ci.yaml'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t riyajoshi/gitverse-frontend:latest .

      - name: Push Docker image
        run: docker push riyajoshi/gitverse-frontend:latest

  update-helm:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update image tag in Helm values
        run: |
          yq e '.image.tag = "latest"' -i k8s/helm/values.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/helm/values.yaml
          git commit -m "ci: update image tag to latest"
          git push

  argocd-sync:
    runs-on: ubuntu-latest
    needs: update-helm
    steps:
      - name: Sync ArgoCD App
        env:
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          curl -k -H "Authorization: Bearer $ARGOCD_AUTH_TOKEN" \
          -X POST https://<your-argocd-server>/api/v1/applications/gitverse/sync
